/*
 * This file is generated by jOOQ.
 */
package hackathon.generation.tool.model;


import hackathon.generation.tool.model.tables.ForeignKeysViewTable;
import hackathon.generation.tool.model.tables.ColumnsViewTable;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.foreign_keys_view</code>.
     */
    public final ForeignKeysViewTable FOREIGN_KEYS_VIEW = ForeignKeysViewTable.FOREIGN_KEYS_VIEW;

    /**
     * The table <code>public.table_columns_view</code>.
     */
    public final ColumnsViewTable TABLE_COLUMNS_VIEW = ColumnsViewTable.COLUMNS_VIEW;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ForeignKeysViewTable.FOREIGN_KEYS_VIEW,
            ColumnsViewTable.COLUMNS_VIEW
        );
    }
}
