/*
 * This file is generated by jOOQ.
 */
package hackathon.generation.tool.model;


import hackathon.generation.tool.model.tables.ForeignKeysViewTable;
import hackathon.generation.tool.model.tables.ColumnsViewTable;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.foreign_keys_view</code>.
     */
    public static final ForeignKeysViewTable FOREIGN_KEYS_VIEW = ForeignKeysViewTable.FOREIGN_KEYS_VIEW;

    /**
     * The table <code>public.table_columns_view</code>.
     */
    public static final ColumnsViewTable TABLE_COLUMNS_VIEW = ColumnsViewTable.COLUMNS_VIEW;
}
